
(function(){
  'use strict';
  const VERSION='20.0.0-master-family-discipleship';
  const $=(s,r=document)=>r.querySelector(s);
  const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const esc=v=>String(v==null?'':v).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
  const arr=v=>Array.isArray(v)?v:[];
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
  const todayISO=()=>new Date().toISOString().slice(0,10);
  const todayLong=()=>new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long',year:'numeric'});
  const emit=msg=>{try{typeof showToast==='function'?showToast(msg):console.log(msg);}catch(e){console.log(msg);}};
  const state=()=>{try{return S;}catch(e){window.S=window.S||{};return window.S;}};
  function safeSave(){try{if(typeof save==='function')save();else localStorage.setItem('mnmd_v5',JSON.stringify(state()));}catch(e){console.warn('save failed',e);}}
  function currentProfile(){const s=state();return s.activeProf||'marcus';}
  function profileName(p=currentProfile()){const s=state();return p==='ingrid'?(s.nameHer||'Ingrid'):(s.nameHim||'Marcus');}
  function uniqDays(days){return Array.from(new Set(arr(days).map(Number).filter(n=>n>0&&n<=365))).sort((a,b)=>a-b);}
  function dayOfYear(){try{if(typeof doy==='function')return clamp(doy(),1,365);}catch(e){}const n=new Date(),s=new Date(n.getFullYear(),0,0);return clamp(Math.floor((n-s)/86400000),1,365);}
  function planDay(){try{if(typeof todayPlanDay==='function')return todayPlanDay();}catch(e){}return dayOfYear();}
  function planLabel(day=planDay()){try{const p=PLAN&&PLAN[day-1];return p&&p.chList?p.chList:`Dia ${day}`;}catch(e){return `Dia ${day}`;}}
  function completedFor(p=currentProfile()){const s=state();return uniqDays(s.profiles&&s.profiles[p]?s.profiles[p].completedDays:[]);}
  function sharedCompleted(){const m=new Set(completedFor('marcus')),i=new Set(completedFor('ingrid'));return Array.from(m).filter(x=>i.has(x)).sort((a,b)=>a-b);}
  function ensure(){const s=state();s.v20=s.v20||{};const v=s.v20;
    v.version=VERSION;
    v.dailyFlow=v.dailyFlow||{};
    v.studyNotes=v.studyNotes||{};
    v.familyPrayers=arr(v.familyPrayers);
    v.monthlyGoals=arr(v.monthlyGoals);
    v.memoryVerses=arr(v.memoryVerses);
    v.principles=arr(v.principles);
    v.backups=arr(v.backups);
    v.reports=arr(v.reports);
    v.syncQueue=arr(v.syncQueue);
    v.reminders=arr(v.reminders);
    v.coupleCovenant=v.coupleCovenant||'Caminhar com Deus, amar com aliança e edificar nosso lar todos os dias.';
    v.familyMembers=v.familyMembers||[
      {id:'marcus',name:s.nameHim||'Marcus',role:'Esposo',icon:'🤵',focus:'Liderança espiritual com amor e constância'},
      {id:'ingrid',name:s.nameHer||'Ingrid',role:'Esposa',icon:'👰',focus:'Sabedoria, paz e edificação do lar'},
      {id:'arthur',name:'Arthur',role:'Filho',icon:'🧒',focus:'Proteção, saúde, alegria e crescimento no caminho do Senhor'}
    ];
    v.familyMembers[0].name=s.nameHim||v.familyMembers[0].name||'Marcus';
    v.familyMembers[1].name=s.nameHer||v.familyMembers[1].name||'Ingrid';
    if(!v.principles.length){v.principles=[
      {title:'Cristo no centro',text:'Toda decisão importante deve passar por oração, Palavra e paz no lar.'},
      {title:'Aliança antes de agenda',text:'A rotina não pode engolir o cuidado mútuo, a conversa e a reconciliação.'},
      {title:'Casa como altar',text:'O lar deve ser lugar de bênção, ensino, perdão e presença de Deus.'},
      {title:'Constância pequena',text:'É melhor uma prática simples todos os dias do que grandes planos abandonados.'}
    ];}
    return v;
  }
  const FLOW_STEPS=[
    {id:'versiculo',ic:'✨',title:'Receber o versículo',sub:'Leia o versículo do dia com atenção.',pts:8,action:()=>goTo('inicio')},
    {id:'leitura',ic:'📜',title:'Leitura bíblica',sub:'Abra a leitura cronológica de hoje.',pts:18,action:()=>openToday()},
    {id:'estudo',ic:'🔎',title:'Estudo e aplicação',sub:'Observe, interprete e aplique ao casamento.',pts:14,action:()=>goTo('estudo')},
    {id:'oracao',ic:'🙏',title:'Oração do casal',sub:'Orem juntos pelo lar e pela missão do dia.',pts:14,action:()=>goTo('oracao')},
    {id:'missao',ic:'💍',title:'Missão de amor',sub:'Faça uma atitude concreta de serviço e carinho.',pts:12,action:()=>goTo('rotina')},
    {id:'gratidao',ic:'📝',title:'Gratidão no diário',sub:'Registre o que Deus fez hoje.',pts:12,action:()=>openDiaryModal()},
    {id:'familia',ic:'🏠',title:'Família no altar',sub:'Ore por Marcus, Ingrid, Arthur e pela casa.',pts:12,action:()=>goTo('familia')},
    {id:'checkin',ic:'🤝',title:'Check-in espiritual',sub:'Conversem antes de encerrar o dia.',pts:10,action:()=>goTo('rotina')}
  ];
  function flowKey(date=todayISO(),prof=currentProfile()){return `${date}_${prof}`;}
  function flow(date=todayISO(),prof=currentProfile()){const v=ensure();const k=flowKey(date,prof);v.dailyFlow[k]=v.dailyFlow[k]||{done:[],mood:5,peace:5,unity:5,note:'',updatedAt:Date.now()};v.dailyFlow[k].done=arr(v.dailyFlow[k].done);return v.dailyFlow[k];}
  function flowScore(date=todayISO(),prof=currentProfile()){const f=flow(date,prof);let n=0;FLOW_STEPS.forEach(st=>{if(f.done.includes(st.id))n+=st.pts;});return clamp(n,0,100);}
  function weekDates(){const res=[];const d=new Date();for(let i=6;i>=0;i--){const x=new Date(d);x.setDate(d.getDate()-i);res.push(x.toISOString().slice(0,10));}return res;}
  function monthKey(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;}
  function monthName(){return new Date().toLocaleDateString('pt-BR',{month:'long',year:'numeric'});}
  function goTo(v){try{if(typeof go==='function'){go(v,null);return;}}catch(e){}$$('.view').forEach(x=>x.classList.remove('active'));const el=$('#view-'+v);if(el)el.classList.add('active');}
  function openToday(){try{if(typeof openDay==='function'){openDay(planDay());return;}}catch(e){}goTo('biblia');}
  function openDiaryModal(){try{if(typeof openM==='function'){openM('diary');return;}}catch(e){}goTo('diario');}
  function addView(id,rootId){const main=$('main');if(!main||$('#view-'+id))return;main.insertAdjacentHTML('beforeend',`<section id="view-${id}" class="view"><div id="${rootId}" class="v20-zone v20-full"></div></section>`);}
  function miniNav(){return `<div class="v20-mini"><button class="v20-btn alt" onclick="ECV20.open('rotina')">🌅 Rotina guiada</button><button class="v20-btn alt" onclick="ECV20.open('estudo')">🔎 Estudo bíblico</button><button class="v20-btn alt" onclick="ECV20.open('familia')">🏠 Família</button><button class="v20-btn alt" onclick="ECV20.open('busca-biblia')">🔍 Busca bíblica</button><button class="v20-btn alt" onclick="ECV20.open('relatorios')">📊 Relatórios</button><button class="v20-btn alt" onclick="ECV20.command()">⌘ Central</button></div>`;}
  function renderHome(){const home=$('#view-inicio');if(!home)return;let mount=$('#v20-home-master');if(!mount){home.insertAdjacentHTML('afterbegin','<div id="v20-home-master" class="v20-zone"></div>');mount=$('#v20-home-master');}
    const score=flowScore(),today=planDay(),missed=missingDays().length,week=weekDates().map(d=>flowScore(d,currentProfile())).reduce((a,b)=>a+b,0)/7;
    const s=state();const prayers=arr(s.prayers).filter(p=>p&&!p.answered).length;const diaryToday=arr(s.diary).some(e=>e&&String(e.date||'').slice(0,10)===todayISO());
    const covenant=ensure().coupleCovenant;
    mount.innerHTML=`${miniNav()}<div class="v20-hero"><div class="v20-grid-desktop"><div><div class="v20-k">V20 · discipulado do casal</div><div class="v20-title">Hoje é dia de conduzir a casa em fé, amor e constância.</div><div class="v20-sub">${esc(covenant)}</div><div class="v20-actions"><button class="v20-btn" onclick="ECV20.open('rotina')">Começar rotina de hoje</button><button class="v20-btn alt" onclick="ECV20.openToday()">Abrir leitura · Dia ${today}</button></div></div><div class="v20-card" style="box-shadow:none;margin:0;background:rgba(255,255,255,.12);border-color:rgba(255,255,255,.22)"><div class="v20-k">placar espiritual</div><div style="display:flex;align-items:center;gap:15px"><div class="v20-score" style="--p:${score*3.6}deg"><span>${score}</span></div><div><div class="v20-sub" style="margin:0;color:rgba(255,255,255,.78)">${profileName()} · ${todayLong()}</div><div class="v20-progress" style="margin-top:10px;background:rgba(255,255,255,.20)"><span style="width:${score}%"></span></div><div class="v20-sub" style="color:rgba(255,255,255,.78)">${score>=80?'Dia muito forte.':'Ainda há passos simples para completar hoje.'}</div></div></div></div></div></div>
    <div class="v20-grid3"><div class="v20-metric"><b>${sharedCompleted().length}</b><span>dias juntos</span><small>lidos por Marcus e Ingrid</small></div><div class="v20-metric"><b>${missed}</b><span>pendências</span><small>${missed?'há dias para recuperar':'plano em dia'}</small></div><div class="v20-metric"><b>${prayers}</b><span>orações ativas</span><small>${diaryToday?'diário registrado hoje':'registre gratidão hoje'}</small></div></div>
    <div class="v20-card"><div class="v20-k">roteiro rápido</div><div class="v20-title" style="font-size:23px">O que fazer agora?</div><div class="v20-flow" style="margin-top:12px">${FLOW_STEPS.slice(0,4).map(stepHtml).join('')}</div><div class="v20-actions"><button class="v20-btn good" onclick="ECV20.markEssentials()">Concluir essenciais</button><button class="v20-btn alt" onclick="ECV20.open('rotina')">Ver rotina completa</button></div></div>`;
  }
  function stepHtml(st){const f=flow(),done=f.done.includes(st.id);return `<div class="v20-step ${done?'done':''}" onclick="ECV20.toggleStep('${st.id}')"><div class="chk">${done?'✓':''}</div><div class="ic">${st.ic}</div><div class="tx"><b>${esc(st.title)}</b><small>${esc(st.sub)}</small></div><div class="pts">+${st.pts}</div></div>`;}
  function toggleStep(id){const f=flow();const i=f.done.indexOf(id);if(i>=0){f.done.splice(i,1);emit('Passo desmarcado');}else{f.done.push(id);emit('Passo concluído ✦');const st=FLOW_STEPS.find(x=>x.id===id);if(st&&st.action)setTimeout(st.action,150);}f.updatedAt=Date.now();queue('dailyFlow',flowKey(),f);safeSave();renderAllSoft();}
  function markEssentials(){const f=flow();['versiculo','leitura','oracao','gratidao'].forEach(id=>{if(!f.done.includes(id))f.done.push(id);});f.updatedAt=Date.now();queue('dailyFlow',flowKey(),f);safeSave();emit('Essenciais marcados para hoje ✦');renderAllSoft();}
  function renderRoutine(){const root=$('#v20-routine-root');if(!root)return;const score=flowScore();const f=flow();const week=weekDates();const avg=Math.round(week.map(d=>flowScore(d,currentProfile())).reduce((a,b)=>a+b,0)/week.length);
    root.innerHTML=`${miniNav()}<div class="v20-hero"><div class="v20-k">rotina diária guiada</div><div class="v20-title">Um caminho simples para hoje.</div><div class="v20-sub">Siga em ordem: Palavra, estudo, oração, missão de amor, gratidão, família e check-in.</div><div class="v20-actions"><button class="v20-btn" onclick="ECV20.markEssentials()">Concluir essenciais</button><button class="v20-btn alt" onclick="ECV20.openToday()">Leitura de hoje</button></div></div><div class="v20-grid-desktop"><div><div class="v20-card"><div class="v20-k">Hoje · ${profileName()}</div><div style="display:flex;gap:15px;align-items:center"><div class="v20-score" style="--p:${score*3.6}deg"><span>${score}</span></div><div style="flex:1"><div class="v20-title" style="font-size:24px">${score>=80?'Dia quase completo':'Continue com calma'}</div><div class="v20-sub">Média dos últimos 7 dias: ${avg}/100.</div><div class="v20-progress" style="margin-top:10px"><span style="width:${score}%"></span></div></div></div></div><div class="v20-card"><div class="v20-k">passos do discipulado</div><div class="v20-flow">${FLOW_STEPS.map(stepHtml).join('')}</div></div></div><div><div class="v20-card"><div class="v20-k">check-in espiritual</div><label class="v20-label">Paz interior</label><input class="v20-input" type="range" min="1" max="10" value="${Number(f.peace||5)}" oninput="ECV20.setCheck('peace',this.value)"><label class="v20-label">Unidade do casal</label><input class="v20-input" type="range" min="1" max="10" value="${Number(f.unity||5)}" oninput="ECV20.setCheck('unity',this.value)"><label class="v20-label">Ânimo espiritual</label><input class="v20-input" type="range" min="1" max="10" value="${Number(f.mood||5)}" oninput="ECV20.setCheck('mood',this.value)"><label class="v20-label">Nota do dia</label><textarea id="v20-check-note" class="v20-textarea" placeholder="Como foi nossa caminhada com Deus hoje?">${esc(f.note||'')}</textarea><div class="v20-actions"><button class="v20-btn" onclick="ECV20.saveCheck()">Salvar check-in</button><button class="v20-btn alt" onclick="ECV20.saveCheckToDiary()">Enviar ao diário</button></div></div><div class="v20-card"><div class="v20-k">recuperação</div>${recoveryHtml()}</div></div></div>`;
  }
  function setCheck(k,v){const f=flow();f[k]=Number(v);f.updatedAt=Date.now();safeSave();}
  function saveCheck(){const f=flow();const n=$('#v20-check-note');if(n)f.note=n.value.trim();f.updatedAt=Date.now();queue('checkin',flowKey(),f);safeSave();emit('Check-in salvo ✦');renderHome();}
  function saveCheckToDiary(){saveCheck();const f=flow();const s=state();s.diary=arr(s.diary);s.diary.unshift({id:'v20-check-'+Date.now(),date:new Date().toISOString(),title:'Check-in espiritual do casal',body:`Paz: ${f.peace}/10. Unidade: ${f.unity}/10. Ânimo: ${f.mood}/10.\n\n${f.note||''}`,mood:'🤝',category:'Check-in'});queue('diary','checkin-'+Date.now(),s.diary[0]);safeSave();emit('Check-in enviado ao diário ✦');}
  function missingDays(){const set=new Set(completedFor(currentProfile()));const d=planDay();const res=[];for(let i=1;i<=d;i++)if(!set.has(i))res.push(i);return res;}
  function recoveryHtml(){const m=missingDays();if(!m.length)return `<div class="v20-alert good">Sua leitura está em dia para ${profileName()}.</div>`;const days=m.slice(0,10);return `<div class="v20-alert">${m.length} dia(s) pendente(s). Recomendo recuperar em blocos pequenos, sem culpa e com constância.</div><div class="v20-list">${days.map(d=>`<div class="v20-note"><b>Dia ${d}</b><p>${esc(planLabel(d))}</p><div class="v20-actions"><button class="v20-btn alt" onclick="ECV20.openDay(${d})">Abrir</button><button class="v20-btn good" onclick="ECV20.markDay(${d})">Marcar lido</button></div></div>`).join('')}</div>${m.length>10?`<div class="v20-sub">Mostrando 10 de ${m.length} pendências.</div>`:''}`;}
  function openDayV(day){try{if(typeof openDay==='function')openDay(day);else goTo('biblia');}catch(e){goTo('biblia');}}
  function markDay(day){try{if(typeof markRead==='function')markRead(day);else{const s=state();s.profiles=s.profiles||{};s.profiles[currentProfile()]=s.profiles[currentProfile()]||{completedDays:[]};s.profiles[currentProfile()].completedDays=uniqDays(arr(s.profiles[currentProfile()].completedDays).concat([day]));safeSave();}}catch(e){}emit('Leitura marcada ✦');renderAllSoft();}
  async function aiText(prompt,maxTokens=1600){try{const key=typeof openAIKey==='function'?openAIKey():'';const model=typeof openAIModel==='function'?openAIModel():'gpt-5-mini';if(!key)throw new Error('sem chave');const endpoint=(typeof OPENAI_ENDPOINT!=='undefined'?OPENAI_ENDPOINT:'https://api.openai.com/v1/responses');const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+key},body:JSON.stringify({model,store:false,max_output_tokens:maxTokens,instructions:'Você é um assistente cristão para um aplicativo devocional de casal. Responda em português do Brasil, com tom bíblico, pastoral, prático e adequado para leitura no celular. Não invente versículos. Use formatação leve.',input:prompt})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error((data.error&&data.error.message)||('Erro HTTP '+r.status));let txt='';try{txt=typeof extractOpenAIText==='function'?extractOpenAIText(data):data.output_text;}catch(e){txt=data.output_text||'';}if(!txt)throw new Error('resposta vazia');return txt.trim();}catch(e){throw e;}}
  function studyPrompt(){const day=Number(($('#v20-study-day')||{}).value)||planDay();const passage=($('#v20-study-passage')||{}).value.trim()||planLabel(day);const theme=($('#v20-study-theme')||{}).value||'Casamento e família';return `Faça um estudo bíblico pastoral para Marcus e Ingrid. Texto/leitura: ${passage}. Dia do plano: ${day}. Tema principal: ${theme}. Estruture em: 1) contexto histórico, 2) observação do texto, 3) interpretação, 4) como aponta para Deus/Cristo, 5) aplicação para casamento e família, 6) perguntas para conversa, 7) oração final. Seja profundo, mas claro.`;}
  function renderStudy(){const root=$('#v20-study-root');if(!root)return;const v=ensure();const day=planDay();const key=`${todayISO()}_${currentProfile()}`;const saved=v.studyNotes[key]||{};
    root.innerHTML=`${miniNav()}<div class="v20-hero"><div class="v20-k">estudo bíblico</div><div class="v20-title">Transforme leitura em entendimento e prática.</div><div class="v20-sub">Método simples: observar, interpretar, enxergar Cristo, aplicar ao casamento e orar.</div></div><div class="v20-grid-desktop"><div><div class="v20-card"><div class="v20-k">leitura de referência</div><label class="v20-label">Dia do plano</label><input id="v20-study-day" class="v20-input" type="number" min="1" max="365" value="${day}"><label class="v20-label">Texto ou tema da leitura</label><input id="v20-study-passage" class="v20-input" value="${esc(saved.passage||planLabel(day))}"><label class="v20-label">Foco do estudo</label><select id="v20-study-theme" class="v20-select"><option>Casamento e família</option><option>Oração</option><option>Perdão</option><option>Paternidade</option><option>Finanças</option><option>Trabalho</option><option>Ansiedade</option><option>Santidade</option></select><div class="v20-actions"><button class="v20-btn" onclick="ECV20.generateStudy()">Gerar estudo com IA</button><button class="v20-btn alt" onclick="ECV20.openToday()">Abrir Bíblia</button></div></div><div class="v20-card"><div class="v20-k">método de estudo</div>${['Observação: o que o texto diz?','Interpretação: o que significava no contexto?','Cristo: o que revela sobre Deus e redenção?','Aplicação: o que faremos hoje?','Oração: como responderemos a Deus?'].map(x=>`<div class="v20-note"><b>${esc(x.split(':')[0])}</b><p>${esc(x.split(':').slice(1).join(':').trim())}</p></div>`).join('')}</div></div><div><div class="v20-card"><div class="v20-k">anotações</div><label class="v20-label">O que Deus ensinou?</label><textarea id="v20-study-note" class="v20-textarea" placeholder="Escreva observações, aplicações e decisões...">${esc(saved.note||'')}</textarea><div class="v20-actions"><button class="v20-btn good" onclick="ECV20.saveStudy()">Salvar estudo</button><button class="v20-btn alt" onclick="ECV20.studyToDiary()">Enviar ao diário</button></div></div><div id="v20-study-ai">${saved.ai?`<div class="v20-card"><div class="v20-k">estudo gerado</div><div class="v20-note"><p>${esc(saved.ai).replace(/\n/g,'<br>')}</p></div></div>`:''}</div></div></div>`;
  }
  async function generateStudy(){const box=$('#v20-study-ai');if(box)box.innerHTML='<div class="v20-card"><div class="csvl"><div class="csvsp"></div><div class="csvt">Gerando estudo bíblico<span class="dots"></span></div></div></div>';try{const txt=await aiText(studyPrompt(),2600);const key=`${todayISO()}_${currentProfile()}`;const v=ensure();v.studyNotes[key]=v.studyNotes[key]||{};v.studyNotes[key].ai=txt;v.studyNotes[key].passage=($('#v20-study-passage')||{}).value||planLabel();v.studyNotes[key].updatedAt=Date.now();queue('study',key,v.studyNotes[key]);safeSave();if(box)box.innerHTML=`<div class="v20-card"><div class="v20-k">estudo gerado</div><div class="v20-note"><p>${esc(txt).replace(/\n/g,'<br>')}</p></div><div class="v20-actions"><button class="v20-btn alt" onclick="ECV20.studyToDiary()">Enviar ao diário</button></div></div>`;}catch(e){if(box)box.innerHTML=`<div class="v20-card"><div class="v20-alert bad">Não consegui gerar pela IA agora. Motivo: ${esc(e.message||e)}</div></div>`;}}
  function saveStudy(){const key=`${todayISO()}_${currentProfile()}`,v=ensure();v.studyNotes[key]=v.studyNotes[key]||{};v.studyNotes[key].passage=($('#v20-study-passage')||{}).value||planLabel();v.studyNotes[key].note=($('#v20-study-note')||{}).value.trim();v.studyNotes[key].updatedAt=Date.now();queue('study',key,v.studyNotes[key]);safeSave();emit('Estudo salvo ✦');}
  function studyToDiary(){saveStudy();const key=`${todayISO()}_${currentProfile()}`,v=ensure(),n=v.studyNotes[key]||{},s=state();s.diary=arr(s.diary);s.diary.unshift({id:'v20-study-'+Date.now(),date:new Date().toISOString(),title:'Estudo bíblico do dia',body:`Texto: ${n.passage||planLabel()}\n\n${n.note||''}\n\n${n.ai||''}`.trim(),mood:'🔎',category:'Estudo'});queue('diary','study-'+Date.now(),s.diary[0]);safeSave();emit('Estudo enviado ao diário ✦');}
  function renderFamily(){const root=$('#v20-family-root');if(!root)return;const v=ensure();
    root.innerHTML=`${miniNav()}<div class="v20-hero"><div class="v20-k">nossa casa servirá ao senhor</div><div class="v20-title">Família no altar: Marcus, Ingrid e Arthur.</div><div class="v20-sub">Uma área para princípios da casa, oração pelos membros da família, metas do mês e memória espiritual.</div></div><div class="v20-grid-desktop"><div><div class="v20-card"><div class="v20-k">cobertura espiritual</div>${v.familyMembers.map(m=>`<div class="v20-family-card"><div class="v20-avatar">${esc(m.icon)}</div><div><b>${esc(m.name)}</b><div class="v20-sub" style="margin:2px 0 0">${esc(m.role)} · ${esc(m.focus)}</div></div><div class="v20-actions"><button class="v20-btn alt" onclick="ECV20.quickFamilyPrayer('${esc(m.id)}')">Orar</button></div></div>`).join('')}</div><div class="v20-card"><div class="v20-k">princípios da casa</div><div class="v20-list">${v.principles.map((p,i)=>`<div class="v20-note"><b>${esc(p.title)}</b><p>${esc(p.text)}</p><small><button class="v20-btn alt" style="min-height:32px" onclick="ECV20.removePrinciple(${i})">Remover</button></small></div>`).join('')}</div><label class="v20-label">Novo princípio</label><input id="v20-pr-title" class="v20-input" placeholder="Ex: Honrar a Deus nas finanças"><textarea id="v20-pr-text" class="v20-textarea" placeholder="Explique o princípio da família..." style="margin-top:8px"></textarea><div class="v20-actions"><button class="v20-btn" onclick="ECV20.addPrinciple()">Adicionar princípio</button></div></div></div><div><div class="v20-card"><div class="v20-k">metas espirituais de ${monthName()}</div><div id="v20-goals-list">${goalsHtml()}</div><label class="v20-label">Nova meta</label><input id="v20-goal-title" class="v20-input" placeholder="Ex: Orar juntos 20 dias este mês"><div class="v20-actions"><button class="v20-btn" onclick="ECV20.addGoal()">Adicionar meta</button></div></div><div class="v20-card"><div class="v20-k">orações da família</div><label class="v20-label">Pedido ou gratidão</label><textarea id="v20-family-prayer" class="v20-textarea" placeholder="Ex: Senhor, guarda o Arthur, fortalece nosso casamento..."></textarea><div class="v20-actions"><button class="v20-btn good" onclick="ECV20.addFamilyPrayer()">Registrar oração</button><button class="v20-btn alt" onclick="ECV20.familyPrayerAI()">Gerar oração IA</button></div><div class="v20-list" style="margin-top:12px">${arr(v.familyPrayers).slice(0,8).map(p=>`<div class="v20-note"><b>${esc(p.title||'Oração da família')}</b><p>${esc(p.text||'')}</p><small>${new Date(p.date||Date.now()).toLocaleString('pt-BR')}</small></div>`).join('')||'<div class="v20-alert">Nenhuma oração familiar registrada ainda.</div>'}</div></div></div></div>`;
  }
  function goalsHtml(){const v=ensure(),mk=monthKey();const goals=arr(v.monthlyGoals).filter(g=>g.month===mk);if(!goals.length)return '<div class="v20-alert">Nenhuma meta para este mês. Crie uma meta simples e mensurável.</div>';return goals.map((g,i)=>`<div class="v20-note"><b>${esc(g.title)}</b><div class="v20-kpi-bar" style="margin-top:8px"><span style="width:${clamp(g.progress||0,0,100)}%"></span><b>${g.progress||0}%</b></div><div class="v20-actions"><button class="v20-btn alt" onclick="ECV20.goalProgress('${g.id}',10)">+10%</button><button class="v20-btn alt" onclick="ECV20.goalProgress('${g.id}',25)">+25%</button><button class="v20-btn good" onclick="ECV20.goalDone('${g.id}')">Concluir</button></div></div>`).join('');}
  function addGoal(){const title=($('#v20-goal-title')||{}).value?.trim();if(!title){emit('Digite uma meta');return;}ensure().monthlyGoals.unshift({id:'goal-'+Date.now(),month:monthKey(),title,progress:0,createdAt:Date.now()});queue('goal','goal-'+Date.now(),{title});safeSave();renderFamily();emit('Meta adicionada ✦');}
  function goalProgress(id,n){const g=ensure().monthlyGoals.find(x=>x.id===id);if(g){g.progress=clamp((g.progress||0)+n,0,100);safeSave();renderFamily();}}
  function goalDone(id){const g=ensure().monthlyGoals.find(x=>x.id===id);if(g){g.progress=100;g.doneAt=Date.now();safeSave();renderFamily();emit('Meta concluída ✦');}}
  function addPrinciple(){const t=($('#v20-pr-title')||{}).value?.trim(),x=($('#v20-pr-text')||{}).value?.trim();if(!t||!x){emit('Preencha título e texto');return;}ensure().principles.push({title:t,text:x});safeSave();renderFamily();emit('Princípio salvo ✦');}
  function removePrinciple(i){ensure().principles.splice(i,1);safeSave();renderFamily();}
  function addFamilyPrayer(text,title){const input=$('#v20-family-prayer');const content=(text||input?.value||'').trim();if(!content){emit('Escreva uma oração');return;}ensure().familyPrayers.unshift({id:'fp-'+Date.now(),title:title||'Oração da família',text:content,date:new Date().toISOString()});if(input)input.value='';queue('familyPrayer','fp-'+Date.now(),content);safeSave();renderFamily();emit('Oração da família registrada ✦');}
  function quickFamilyPrayer(id){const m=ensure().familyMembers.find(x=>x.id===id);if(!m)return;addFamilyPrayer(`Senhor, colocamos ${m.name} diante de Ti. Cuida da sua vida, fortalece sua fé, protege seus caminhos e cumpre Teus propósitos em nossa família. Amém.`,`Oração por ${m.name}`);}
  async function familyPrayerAI(){const box=$('#v20-family-prayer');if(box)box.value='Gerando oração...';try{const txt=await aiText(`Crie uma oração curta e profunda pela família de Marcus, Ingrid e Arthur. Inclua casamento, proteção, saúde, provisão, sabedoria e presença de Deus no lar.`,1000);if(box)box.value=txt;}catch(e){if(box)box.value='Senhor, colocamos nossa família diante de Ti. Guarda nosso casamento, cuida do Arthur, fortalece nossa fé, dá-nos sabedoria e faz da nossa casa um lugar de paz, amor e presença de Deus. Amém.';}}
  function queue(type,id,payload){const v=ensure();v.syncQueue.push({type,id,ts:Date.now(),profile:currentProfile(),payload});if(v.syncQueue.length>120)v.syncQueue=v.syncQueue.slice(-120);}

  function norm(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();}
  function renderBibleSearch(){const root=$('#v20-bible-search-root');if(!root)return;const hist=arr(ensure().bibleSearchHistory).slice(0,8);root.innerHTML=`${miniNav()}<div class="v20-hero"><div class="v20-k">busca bíblica local</div><div class="v20-title">Encontre palavras, temas e versículos.</div><div class="v20-sub">A busca usa o arquivo local da Bíblia ACF quando ele está disponível no aparelho.</div></div><div class="v20-card"><label class="v20-label">Buscar na Bíblia</label><div class="v20-grid" style="grid-template-columns:1fr auto"><input id="v20-bible-q" class="v20-input" placeholder="Ex: amor, fé, não temas, sabedoria" onkeydown="if(event.key==='Enter')ECV20.searchBible()"><button class="v20-btn" onclick="ECV20.searchBible()">Buscar</button></div>${hist.length?`<div class="v20-actions">${hist.map(h=>`<button class="v20-btn alt" onclick="ECV20.searchBible('${esc(h).replace(/'/g,'&#39;')}')">${esc(h)}</button>`).join('')}</div>`:''}</div><div id="v20-bible-results" class="v20-list"></div>`;}
  async function searchBible(q){q=(q||($('#v20-bible-q')||{}).value||'').trim();if(!q){emit('Digite uma palavra para buscar');return;}const root=$('#v20-bible-results');if(root)root.innerHTML='<div class="v20-card"><div class="csvl"><div class="csvsp"></div><div class="csvt">Buscando na Bíblia<span class="dots"></span></div></div></div>';const v=ensure();v.bibleSearchHistory=[q].concat(arr(v.bibleSearchHistory).filter(x=>x!==q)).slice(0,8);safeSave();try{const idx=await loadBible();const qn=norm(q);const hits=[];const books=(typeof BOOKS!=='undefined'?BOOKS:[]);for(const ab in idx){const book=(books.find(b=>b.a===ab)||{n:ab}).n;for(const ch in idx[ab]){for(const vs of idx[ab][ch]){const tx=String(vs.t||'');if(norm(tx).includes(qn)){hits.push({book,ch,v:vs.v,t:tx});if(hits.length>=100)break;}}if(hits.length>=100)break;}if(hits.length>=100)break;}if(!root)return;if(!hits.length){root.innerHTML='<div class="v20-card"><div class="v20-alert">Nenhum resultado encontrado. Tente outra palavra ou expressão.</div></div>';return;}const re=new RegExp('('+q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+')','ig');root.innerHTML=`<div class="v20-card"><div class="v20-k">resultado</div><div class="v20-title" style="font-size:23px">${hits.length} ocorrência(s)</div><div class="v20-sub">Mostrando até 100 resultados para manter o app leve.</div></div>`+hits.map(h=>`<div class="v20-note" onclick="ECV20.copyVerse('${esc(h.book)} ${h.ch}:${h.v}','${esc(h.t).replace(/'/g,'&#39;')}')" style="cursor:pointer"><b>${esc(h.book)} ${h.ch}:${h.v}</b><p>${esc(h.t).replace(re,'<mark>$1</mark>')}</p><small>Toque para copiar</small></div>`).join('');}catch(e){if(root)root.innerHTML=`<div class="v20-card"><div class="v20-alert bad">Não consegui carregar a Bíblia agora. Verifique se o arquivo biblia-acf.csv está no repositório.</div></div>`;}}
  function copyVerse(ref,txt){const full=`${txt} — ${ref}`;if(navigator.clipboard)navigator.clipboard.writeText(full).then(()=>emit('Versículo copiado ✦'));else emit(full);}

  function reportText(){const s=state(),v=ensure();const m=completedFor('marcus').length,i=completedFor('ingrid').length,shared=sharedCompleted().length;const prayers=arr(s.prayers),diary=arr(s.diary);const active=prayers.filter(p=>p&&!p.answered).length,answered=prayers.filter(p=>p&&p.answered).length;const goals=arr(v.monthlyGoals).filter(g=>g.month===monthKey());const flows=weekDates().map(d=>flowScore(d,currentProfile()));const avg=Math.round(flows.reduce((a,b)=>a+b,0)/flows.length);return `ETERNO COMPROMISSO — RELATÓRIO V20\nData: ${todayLong()}\nFamília: Marcus, Ingrid e Arthur\n\nLEITURA BÍBLICA\n- Marcus: ${m}/365 dias\n- Ingrid: ${i}/365 dias\n- Dias concluídos pelos dois: ${shared}/365\n- Dia atual do plano: ${planDay()} (${planLabel()})\n- Pendências do perfil atual: ${missingDays().length}\n\nROTINA ESPIRITUAL\n- Perfil atual: ${profileName()}\n- Pontuação de hoje: ${flowScore()}/100\n- Média dos últimos 7 dias: ${avg}/100\n\nORAÇÃO E DIÁRIO\n- Pedidos ativos: ${active}\n- Orações respondidas: ${answered}\n- Entradas no diário: ${diary.length}\n- Orações familiares: ${arr(v.familyPrayers).length}\n\nMETAS DO MÊS\n${goals.length?goals.map(g=>`- ${g.title}: ${g.progress||0}%`).join('\n'):'- Nenhuma meta cadastrada'}\n\nALIANÇA DO CASAL\n${v.coupleCovenant}\n\nPRÓXIMO PASSO RECOMENDADO\nAbrir a rotina guiada, concluir a leitura de hoje, orar pela família e registrar uma gratidão.`;}
  function renderReports(){const root=$('#v20-reports-root');if(!root)return;const txt=reportText();const bytes=(()=>{try{return new Blob([JSON.stringify(state())]).size}catch(e){return 0}})();const cache='caches' in window?'suportado':'indisponível';
    root.innerHTML=`${miniNav()}<div class="v20-hero"><div class="v20-k">relatórios e saúde do app</div><div class="v20-title">Acompanhe a evolução espiritual e a integridade dos dados.</div><div class="v20-sub">Relatório semanal/mensal, diagnóstico, backup versionado e manutenção local.</div></div><div class="v20-grid-desktop"><div><div class="v20-card"><div class="v20-k">relatório espiritual</div><div class="v20-report" id="v20-report-text">${esc(txt)}</div><div class="v20-actions"><button class="v20-btn" onclick="ECV20.printReport()">Imprimir / salvar PDF</button><button class="v20-btn alt" onclick="ECV20.copyReport()">Copiar relatório</button><button class="v20-btn alt" onclick="ECV20.saveReportHistory()">Salvar histórico</button></div></div></div><div><div class="v20-card"><div class="v20-k">diagnóstico</div><div class="v20-report">Versão: ${VERSION}\nLocalStorage: ${(bytes/1024).toFixed(1)} KB\nCache/PWA: ${cache}\nFila offline: ${ensure().syncQueue.length}\nBackups versionados: ${ensure().backups.length}\nÚltimo dia: ${todayISO()}</div><div class="v20-actions"><button class="v20-btn good" onclick="ECV20.repair()">Reparar dados</button><button class="v20-btn alt" onclick="ECV20.versionedBackup()">Criar backup</button><button class="v20-btn warn" onclick="ECV20.clearCache()">Limpar cache</button></div></div><div class="v20-card"><div class="v20-k">histórico salvo</div><div class="v20-list">${arr(ensure().reports).slice(0,6).map(r=>`<div class="v20-note"><b>${new Date(r.date).toLocaleString('pt-BR')}</b><p>${esc(String(r.text||'').slice(0,160))}...</p></div>`).join('')||'<div class="v20-alert">Nenhum relatório salvo ainda.</div>'}</div></div></div></div>`;
  }
  function printReport(){goTo('relatorios');setTimeout(()=>window.print(),250);}
  function copyReport(){const txt=reportText();if(navigator.clipboard)navigator.clipboard.writeText(txt).then(()=>emit('Relatório copiado ✦'));else emit('Copie manualmente o relatório');}
  function saveReportHistory(){ensure().reports.unshift({date:new Date().toISOString(),text:reportText()});ensure().reports=ensure().reports.slice(0,24);safeSave();renderReports();emit('Relatório salvo no histórico ✦');}
  function versionedBackup(){const v=ensure();const snap={version:VERSION,date:new Date().toISOString(),state:state()};v.backups.unshift({date:snap.date,bytes:new Blob([JSON.stringify(snap)]).size});v.backups=v.backups.slice(0,12);safeSave();const blob=new Blob([JSON.stringify(snap,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`eterno-compromisso-backup-v20-${todayISO()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);emit('Backup V20 criado ✦');}
  function repair(){const s=state();ensure();s.profiles=s.profiles||{};['marcus','ingrid'].forEach(p=>{s.profiles[p]=s.profiles[p]||{completedDays:[]};s.profiles[p].completedDays=uniqDays(s.profiles[p].completedDays);});s.prayers=arr(s.prayers).filter(Boolean).slice(0,500);s.diary=arr(s.diary).filter(Boolean).slice(0,500);s.completedDevoIds=arr(s.completedDevoIds).slice(0,365);const v=ensure();v.familyPrayers=arr(v.familyPrayers).filter(Boolean).slice(0,300);v.syncQueue=arr(v.syncQueue).slice(-120);v.reports=arr(v.reports).slice(0,24);safeSave();emit('Dados reparados e compactados ✦');renderReports();}
  async function clearCache(){try{if('caches' in window){const keys=await caches.keys();await Promise.all(keys.map(k=>caches.delete(k)));}emit('Cache limpo. Recarregue o app.');}catch(e){emit('Não consegui limpar o cache');}}
  function installCommand(){if($('#v20-command'))return;document.body.insertAdjacentHTML('beforeend',`<div class="v20-drawer"><button class="v20-float" onclick="ECV20.command()" title="Central V20">⌘</button></div><div id="v20-command" class="v20-command" onclick="if(event.target.id==='v20-command')ECV20.command(false)"><div class="v20-command-panel"><div class="v20-k">central rápida</div><div class="v20-title" style="font-size:25px">Eterno Compromisso V20</div><div class="v20-sub">Acesse rapidamente os módulos principais.</div><div class="v20-command-grid" style="margin-top:14px"><button class="v20-btn alt" onclick="ECV20.open('rotina');ECV20.command(false)">🌅 Rotina guiada</button><button class="v20-btn alt" onclick="ECV20.open('estudo');ECV20.command(false)">🔎 Estudo bíblico</button><button class="v20-btn alt" onclick="ECV20.open('familia');ECV20.command(false)">🏠 Família no altar</button><button class="v20-btn alt" onclick="ECV20.open('relatorios');ECV20.command(false)">📊 Relatórios</button><button class="v20-btn alt" onclick="ECV20.open('busca-biblia');ECV20.command(false)">🔍 Busca bíblica</button><button class="v20-btn alt" onclick="ECV20.openToday();ECV20.command(false)">📜 Leitura de hoje</button><button class="v20-btn alt" onclick="openM&&openM('cfg');ECV20.command(false)">⚙️ Configurações</button></div><div class="v20-actions"><button class="v20-btn" onclick="ECV20.command(false)">Fechar</button></div></div></div>`);document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();command();}if(e.key==='Escape')command(false);});}
  function command(show){const el=$('#v20-command');if(!el)return;el.classList.toggle('show',show===undefined?!el.classList.contains('show'):!!show);}
  function installSettingsPatch(){const modal=$('#m-cfg .modal');if(!modal||$('#v20-settings-box'))return;const html=`<div id="v20-settings-box"><div class="cr" style="margin-top:10px"><div><div class="crl">V20 Master Family Discipleship</div><div class="crs">Rotina guiada, família no altar, estudo bíblico, relatórios e backup versionado.</div></div></div><div class="v20-grid" style="margin:10px 0"><button class="v20-btn alt" type="button" onclick="ECV20.open('rotina')">🌅 Rotina</button><button class="v20-btn alt" type="button" onclick="ECV20.open('familia')">🏠 Família</button><button class="v20-btn alt" type="button" onclick="ECV20.open('relatorios')">📊 Relatórios</button><button class="v20-btn alt" type="button" onclick="ECV20.versionedBackup()">💾 Backup V20</button></div><label class="v20-label">Aliança do casal</label><textarea id="v20-covenant" class="v20-textarea" placeholder="Escreva o compromisso espiritual do casal...">${esc(ensure().coupleCovenant)}</textarea><div class="v20-actions"><button class="v20-btn" type="button" onclick="ECV20.saveCovenant()">Salvar aliança</button></div></div>`;const btn=modal.querySelector('button[onclick="saveCfg()"]');if(btn)btn.insertAdjacentHTML('beforebegin',html);else modal.insertAdjacentHTML('beforeend',html);}
  function saveCovenant(){ensure().coupleCovenant=($('#v20-covenant')||{}).value?.trim()||ensure().coupleCovenant;safeSave();emit('Aliança do casal salva ✦');renderHome();}
  function patchRenderers(){if(typeof rHome==='function'&&!rHome.__v20){const old=rHome;window.rHome=rHome=function(){old.apply(this,arguments);try{renderHome();}catch(e){console.warn(e);}};rHome.__v20=true;}if(typeof rProfile==='function'&&!rProfile.__v20){const old=rProfile;window.rProfile=rProfile=function(){old.apply(this,arguments);try{renderProfileAddon();}catch(e){}};rProfile.__v20=true;}if(typeof openM==='function'&&!openM.__v20){const old=openM;window.openM=openM=function(id){old.apply(this,arguments);setTimeout(()=>{try{installSettingsPatch();}catch(e){}},80);};openM.__v20=true;}if(typeof save==='function'&&!save.__v20){const old=save;window.save=save=function(){try{ensure();}catch(e){}return old.apply(this,arguments);};save.__v20=true;}}
  function renderProfileAddon(){const view=$('#view-perfil');if(!view||$('#v20-profile-addon'))return;view.insertAdjacentHTML('beforeend',`<div id="v20-profile-addon" class="v20-card"><div class="v20-k">v20 · central de crescimento</div><div class="v20-title" style="font-size:23px">Ferramentas avançadas</div><div class="v20-actions"><button class="v20-btn alt" onclick="ECV20.open('rotina')">Rotina guiada</button><button class="v20-btn alt" onclick="ECV20.open('estudo')">Estudo bíblico</button><button class="v20-btn alt" onclick="ECV20.open('familia')">Família no altar</button><button class="v20-btn alt" onclick="ECV20.open('busca-biblia')">Busca bíblica</button><button class="v20-btn alt" onclick="ECV20.open('relatorios')">Relatórios</button></div></div>`);}
  function renderAllSoft(){try{renderHome();}catch(e){}try{renderRoutine();}catch(e){}try{renderReports();}catch(e){}try{renderFamily();}catch(e){}}
  function init(){ensure();addView('rotina','v20-routine-root');addView('estudo','v20-study-root');addView('familia','v20-family-root');addView('busca-biblia','v20-bible-search-root');addView('relatorios','v20-reports-root');installCommand();patchRenderers();renderHome();renderRoutine();renderStudy();renderFamily();renderBibleSearch();renderReports();renderProfileAddon();installSettingsPatch();document.body.classList.add('ec-v20-ready');const hv=(location.hash||'').replace('#','');if(['rotina','estudo','familia','relatorios','busca-biblia'].includes(hv))setTimeout(()=>window.ECV20.open(hv),250);}
  window.ECV20={version:VERSION,open:function(v){goTo(v);setTimeout(()=>{if(v==='rotina')renderRoutine();if(v==='estudo')renderStudy();if(v==='familia')renderFamily();if(v==='busca-biblia')renderBibleSearch();if(v==='relatorios')renderReports();},20)},command,openToday,openDay:openDayV,markDay,toggleStep,markEssentials,setCheck,saveCheck,saveCheckToDiary,generateStudy,saveStudy,studyToDiary,quickFamilyPrayer,addFamilyPrayer,familyPrayerAI,addPrinciple,removePrinciple,addGoal,goalProgress,goalDone,printReport,copyReport,saveReportHistory,versionedBackup,repair,clearCache,saveCovenant,searchBible,copyVerse,renderAll:renderAllSoft};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,50));else setTimeout(init,50);
})();
